# Generated by Django 5.2.5 on 2025-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('place_type', models.CharField(choices=[('restaurant', 'RESTAURANT'), ('fast_food', 'FAST FOOD')], default='restaurant', max_length=20)),
                ('etoiles', models.FloatField(default=0.0)),
            ],
        ),
    ]
