# Generated by Django 5.2.5 on 2025-09-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
