# Generated by Django 5.2.5 on 2025-08-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
