# Generated by Django 5.2.5 on 2025-08-30 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0002_user_reset_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token',
        ),
    ]
